<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.PauseScreen</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.PauseScreen</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Common" Version="10.11.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Controller" Version="10.11.0" PrivateAssets="All" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.0" PrivateAssets="All" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/pausescreen.js" />
  </ItemGroup>
</Project>
